// Code generated by goctl. DO NOT EDIT!
// Source: im.proto

package server

import (
	"context"

	"llb-chat/apps/im/rpc/im"
	"llb-chat/apps/im/rpc/internal/logic"
	"llb-chat/apps/im/rpc/internal/svc"
)

type ImServer struct {
	svcCtx *svc.ServiceContext
	im.UnimplementedImServer
}

func NewImServer(svcCtx *svc.ServiceContext) *ImServer {
	return &ImServer{
		svcCtx: svcCtx,
	}
}

// 获取会话记录
func (s *ImServer) GetChatLog(ctx context.Context, in *im.GetChatLogReq) (*im.GetChatLogResp, error) {
	l := logic.NewGetChatLogLogic(ctx, s.svcCtx)
	return l.GetChatLog(in)
}

// 建立会话: 群聊, 私聊
func (s *ImServer) SetUpUserConversation(ctx context.Context, in *im.SetUpUserConversationReq) (*im.SetUpUserConversationResp, error) {
	l := logic.NewSetUpUserConversationLogic(ctx, s.svcCtx)
	return l.SetUpUserConversation(in)
}

// 获取会话
func (s *ImServer) GetConversations(ctx context.Context, in *im.GetConversationsReq) (*im.GetConversationsResp, error) {
	l := logic.NewGetConversationsLogic(ctx, s.svcCtx)
	return l.GetConversations(in)
}

// 更新会话
func (s *ImServer) PutConversations(ctx context.Context, in *im.PutConversationsReq) (*im.PutConversationsResp, error) {
	l := logic.NewPutConversationsLogic(ctx, s.svcCtx)
	return l.PutConversations(in)
}

func (s *ImServer) CreateGroupConversation(ctx context.Context, in *im.CreateGroupConversationReq) (*im.CreateGroupConversationResp, error) {
	l := logic.NewCreateGroupConversationLogic(ctx, s.svcCtx)
	return l.CreateGroupConversation(in)
}
