// Code generated by goctl. DO NOT EDIT.
package types

type ChatLog struct {
	Id             string `json:"id,omitempty"`
	ConversationId string `json:"conversationId,omitempty"`
	SendId         string `json:"sendId,omitempty"`
	RecvId         string `json:"recvId,omitempty"`
	MsgType        int32  `json:"msgType,omitempty"`
	MsgContent     string `json:"msgContent,omitempty"`
	ChatType       int32  `json:"chatType,omitempty"`
	SendTime       int64  `json:"SendTime,omitempty"`
}

type Conversation struct {
	ConversationId string `json:"conversationId,omitempty"`
	ChatType       int32  `json:"ChatType,omitempty"`
	TargetId       string `json:"targetId,omitempty"`
	IsShow         bool   `json:"isShow,omitempty"`
	Seq            int64  `json:"seq,omitempty"`
	Read           int32  `json:"read,omitempty"`
	Total          int32  `json:"total,omitempty"`
	Unread         int32  `json:"unread,omitempty"`
}

type GetChatLogReadRecordsReq struct {
	MsgId string `json:"msgId"`
}

type GetChatLogReadRecordsResp struct {
	Reads   []string `json:"reads"`
	UnReads []string `json:"unReads"`
}

type ChatLogReq struct {
	ConversationId string `json:"conversationId"`
	StartSendTime  int64  `json:"startSendTime,omitempty"`
	EndSendTime    int64  `json:"endSendTime,omitempty"`
	Count          int64  `json:"count,omitempty"`
}

type ChatLogResp struct {
	List []*ChatLog `json:"list"`
}

type GetConversationsReq struct {
}

type GetConversationsResp struct {
	UserId           string                   `json:"userId"`
	ConversationList map[string]*Conversation `json:"conversationList"`
}

type PutConversationsReq struct {
	ConversationList map[string]*Conversation `json:"conversationList"`
}

type PutConversationsResp struct {
}

type SetUpUserConversationReq struct {
	SendId   string `json:"sendId,omitempty"`
	RecvId   string `json:"recvId,omitempty"`
	ChatType int32  `json:"ChatType,omitempty"`
}

type SetUpUserConversationResp struct {
}
